TITLE_STR	=	"LuaEngine";

CONFIG_STR_FILENAME	=	"LuaEngine.ini";

M_CLIENT_LEFT			=	0.0;
M_CLIENT_RIGHT		=	640.0;
M_CLIENT_TOP			=	0.0;
M_CLIENT_BOTTOM		=	480.0;
M_CLIENT_WIDTH		=	(M_CLIENT_RIGHT-M_CLIENT_LEFT);
M_CLIENT_HEIGHT		=	(M_CLIENT_BOTTOM-M_CLIENT_TOP);
M_CLIENT_CENTER_X	=	((M_CLIENT_LEFT+M_CLIENT_RIGHT)/2.0);
M_CLIENT_CENTER_Y	=	((M_CLIENT_TOP+M_CLIENT_BOTTOM)/2.0);

RESCONFIGS_SYSTEM	=	"System";
	RESCONFIGN_USE3DMODE				=	"Use3DMode";
	RESCONFIGDEFAULT_USE3DMODE	=	0;

RESCONFIGS_KEYSETTING	=	"KeySetting";
	RESCONFIGN_KEYUP						=	"KeyUp";
	RESCONFIGDEFAULT_KEYUP			=	DIK_UP;
	RESCONFIGN_KEYDOWN					=	"KeyDown";
	RESCONFIGDEFAULT_KEYDOWN		=	DIK_DOWN;
	RESCONFIGN_KEYLEFT					=	"KeyLeft";
	RESCONFIGDEFAULT_KEYLEFT		=	DIK_LEFT;
	RESCONFIGN_KEYRIGHT					=	"KeyRight";
	RESCONFIGDEFAULT_KEYRIGHT		=	DIK_RIGHT;
	RESCONFIGN_KEYA							=	"KeyA";
	RESCONFIGDEFAULT_KEYA				=	DIK_A;
	RESCONFIGN_KEYS							=	"KeyS";
	RESCONFIGDEFAULT_KEYS				=	DIK_S;
	RESCONFIGN_KEYD							=	"KeyD";
	RESCONFIGDEFAULT_KEYD				=	DIK_D;
	RESCONFIGN_KEYZ							=	"KeyZ";
	RESCONFIGDEFAULT_KEYZ				=	DIK_Z;
	RESCONFIGN_KEYX							=	"KeyX";
	RESCONFIGDEFAULT_KEYX				=	DIK_X;
	RESCONFIGN_KEYC							=	"KeyC";
	RESCONFIGDEFAULT_KEYC				=	DIK_C;
	RESCONFIGN_KEYSPACE					=	"KeySpace";
	RESCONFIGDEFAULT_KEYSPACE		=	DIK_SPACE;
	RESCONFIGN_KEYPAUSE					=	"KeyPause";
	RESCONFIGDEFAULT_KEYPAUSE		=	DIK_ESCAPE;
	RESCONFIGN_KEYSKIP					=	"KeySkip";
	RESCONFIGDEFAULT_KEYSKIP		=	DIK_LCONTROL;
	RESCONFIGN_KEYENTER					=	"KeyEnter";
	RESCONFIGDEFAULT_KEYENTER		=	DIK_RETURN;
	RESCONFIGN_KEYCANCEL				=	"KeyCancel";
	RESCONFIGDEFAULT_KEYCANCEL	=	DIK_DELETE;
	RESCONFIGN_KEYESCAPE				=	"KeyEscape";
	RESCONFIGDEFAULT_KEYESCAPE	=	DIK_F4;
	RESCONFIGN_KEYCAPTURE				=	"KeyCapture";
	RESCONFIGDEFAULT_KEYCAPTURE	=	DIK_HOME;
	RESCONFIGN_KEYBGMDOWN				=	"KeyBGMDown";
	RESCONFIGDEFAULT_KEYBGMDOWN	=	DIK_MINUS;
	RESCONFIGN_KEYBGMUP					=	"KeyBGMUp";
	RESCONFIGDEFAULT_KEYBGMUP		=	DIK_EQUALS;
	RESCONFIGN_KEYSEDOWN				=	"KeySEDown";
	RESCONFIGDEFAULT_KEYSEDOWN	=	DIK_LBRACKET;
	RESCONFIGN_KEYSEUP					=	"KeySEUp";
	RESCONFIGDEFAULT_KEYSEUP		=	DIK_RBRACKET;
	
RESCONFIGS_JOYSETTING	=	"JoySetting";
	RESCONFIGN_JOYPAUSE					=	"JoyPause";
	RESCONFIGDEFAULT_JOYPAUSE		=	1;
	RESCONFIGN_JOYA							=	"JoyA";
	RESCONFIGDEFAULT_JOYA				=	4;
	RESCONFIGN_JOYS							=	"JoyS";
	RESCONFIGDEFAULT_JOYS				=	5;
	RESCONFIGN_JOYD							=	"JoyD";
	RESCONFIGDEFAULT_JOYD				=	6;
	RESCONFIGN_JOYZ							=	"JoyZ";
	RESCONFIGDEFAULT_JOYZ				=	0;
	RESCONFIGN_JOYX							=	"JoyX";
	RESCONFIGDEFAULT_JOYX				=	3;
	RESCONFIGN_JOYC							=	"JoyC";
	RESCONFIGDEFAULT_JOYC				=	2;
	RESCONFIGN_JOYSPACE					=	"JoySpace";
	RESCONFIGDEFAULT_JOYSPACE		=	7;
	RESCONFIGN_JOYENTER					=	"JoyEnter";
	RESCONFIGDEFAULT_JOYENTER		=	3;
	RESCONFIGN_JOYCANCEL				=	"JoyCancel";
	RESCONFIGDEFAULT_JOYCANCEL	=	2;
	RESCONFIGN_JOYSPEEDUP				=	"JoySpeedUp";
	RESCONFIGDEFAULT_JOYSPEEDUP	=	5;

RESCONFIGS_VOLUME		=	"Volume";
	RESCONFIGN_VOLMUSIC				=	"Music";
	RESCONFIGDEFAULT_VOLMUSIC	=	100;
	RESCONFIGN_VOLSE					=	"SE";
	RESCONFIGDEFAULT_VOLSE		=100;

RESCONFIGS_CUSTOM		=	"Custom";
	RESCONFIGN_SCREENMODE				=	"ScreenMode";
	RESCONFIGDEFAULT_SCREENMODE	=	0;
	RESCONFIGN_USERNAME					=	"UserName";
	RESCONFIGDEFAULT_USERNAME		=	"";
	RESCONFIGN_RENDERSKIP				=	"RenderSkip";
	RESCONFIGDEFAULT_RENDERSKIP	=	0;
	RESCONFIGN_DIFFICULT				=	"Difficult";
	RESCONFIGDEFAULT_DIFFICULT	=	2;

RESCONFIGS_CUSTOMWINDOW		=	"CustomWindow";
	RESCONFIGN_DEFAULTWINDOW				=	"DefaultWindow";
	RESCONFIGDEFAULT_DEFAULTWINDOW	=	1;
	RESCONFIGN_WINDOWLEFT						=	"WindowLeft";
	RESCONFIGDEFAULT_WINDOWLEFT			=	0;
	RESCONFIGN_WINDOWTOP						=	"WindowTop";
	RESCONFIGDEFAULT_WINDOWTOP			=	0;
	RESCONFIGN_WINDOWWIDTH					=	"WindowWidth";
	RESCONFIGDEFAULT_WINDOWWIDTH		=	640;
	RESCONFIGN_WINDOWHEIGHT					=	"WindowHeight";
	RESCONFIGDEFAULT_WINDOWHEIGHT		=	480;
	RESCONFIGN_WINDOWTOPMOST				=	"WindowTopMost";
	RESCONFIGDEFAULT_WINDOWTOPMOST	=	0;

RESCONFIGS_RESOURCE				=	"Resource"
	RESCONFIGN_RESOURCEFILE				=	"ResourceFile"
	RESCONFIGDEFAULT_RESOURCEFILE	=	""
	RESCONFIGN_PASSWORD						=	"Password"
	RESCONFIGDEFAULT_PASSWORD			=	"h5nc"

RESDEFAULT_FONTFILE			=	"Graphic/Font/font.fnt"

RESDEFAULT_DATAFOLDER			=	"Data/"
	RESDEFAULT_TEXTUREDEFINE		=	"TextureDefine.table"
	RESDEFAULT_SPRITEITEMDEFINE	=	"SpriteItemDefine.table"
	RESDEFAULT_EFFECTDEFINE			=	"EffectDefine.table"
	RESDEFAULT_SEDEFINE					=	"SEDefine.table"
	RESDEFAULT_MUSICDEFINE			=	"MusicDefine.table"

PQUIT		=	0;
PGO			=	1;
POK			=	2;
PBACK		=	3;
PTURN		=	4;
PSKIP		=	5;
PTITLE	=	6;


STATE_START							=	0;
STATE_PAUSE							=	1;
STATE_CONTINUE					=	2;
STATE_CLEAR							=	3;
STATE_ENDING						=	4;
STATE_TITLE							=	5;
STATE_OVER							=	6;
STATE_REPLAY						=	7;
STATE_RESULT						=	8;
STATE_OPTION						=	9;
STATE_MUSIC							=	10;
STATE_INIT							=	11;

M_KEYKEYMAX	=	0x100;
M_JOYKEYMAX	=	0x20;

RESLOADING_PCK	=	"Graphic/Loading.pck";
RESLOADING_TEX	=	"Loading/Loading.tex";

M_REPLAYFOLDER	=	"Replay/"

M_DEFAULT_PAN = -101
M_DEFAULT_PITCH = -1

M_FFFFFFFF	=	global.ARGB(0xff, 0xffffff);

M_FADETIME	=	16

M_RENDEROVERRANGE	=	-0xffffff;

M_PUSH_FIRST	=	40
M_PUSH_ROLLTO	=	32

SELSAVE_TITLE			=	1;
SELSAVE_DIFFICULT	=	2;
SELSAVE_PAUSE			=	3;
SELSAVE_OVER			=	4;
SELSAVE_CONFIRM		=	5;

M_SE_PAN = 0.35;

M_STAGECOLOR_1	=	0xFF0000;
M_STAGECOLOR_2	=	0x00FF00;
M_STAGECOLOR_3	=	0x0000FF;
M_STAGECOLOR_4	=	0xFFFF00;
M_STAGECOLOR_5	=	0x00FFFF;

M_STAGE_NORMALALPHA			=	0x80;
M_STAGE_NONACTIVEALPHA	=	0x20
M_STAGE_FLASHALPHA			=	0xFF;

M_ALARMTIME = 30
M_DISPLAYTIME = 90

M_BITTEST_1		=	0x0001;
M_BITTEST_2		=	0x0002;
M_BITTEST_3		=	0x0004;
M_BITTEST_4		=	0x0008;
M_BITTEST_5		=	0x0010;
M_BITTEST_6		=	0x0020;
M_BITTEST_7		=	0x0040;
M_BITTEST_8		=	0x0080;
M_BITTEST_9		=	0x0100;
M_BITTEST_10	=	0x0200;
M_BITTEST_11	=	0x0400;
M_BITTEST_12	=	0x0800;
M_BITTEST_13	=	0x1000;
M_BITTEST_14	=	0x2000;
M_BITTEST_15	=	0x4000;
M_BITTEST_16	=	0x8000;

M_BYTETEST_1	=	0x000000FF;
M_BYTETEST_2	=	0x0000FF00;
M_BYTETEST_3	=	0x00FF0000;
M_BYTETEST_4	=	0xFF000000;

M_REPLAYSIGN				=	"RPY"
M_REPLAYMAGICNUMBER	=	0x0A35F345

M_INTTIMEFACTOR	=	10000

M_SCOREPERTIME	=	6

M_FASTFRAMESKIP			= -3
M_DEFAULT_FRAMESKIP	= 1;